cpu: 30
memory: 8Gi
shared_memory: 8Gi
hugepages:
  page_size: 2Mi
  reserved_size: 16Gi
replicaCount: 1
image:
  repository: harbor.rke2-capone-harbor.wclusters.sylva/library/vsr
  tag: 3.10.1.3
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""
ports:
- name: sriov-vsr-nad-pt-vf     # the NAD name created by the 'SriovNetwork' or manually
  resource_name: rancher.io/sriov
day1Config:
  enabled: true
  # licenseKey: "<LICENSE PROVIDED BY WG02 TEAM>"
  hostname: VSR3
  fastPath:
    port: pci-b35s0
  preSharedKey:
    name: secgw
    secret: sylva0123456789
  addresses:
    vpn:
      local: 10.16.3.253
      remote: 10.16.3.250
    trafficSelectors:
      local: 1.1.1.1/32
      remote: 2.2.2.2/32
  ikePolicy:
    template: ike1
    proposalId: 1
    encryptionAlgorithm: aes128-cbc
    authenticationAlgorithm: hmac-sha1
    dhGroup: modp1024
    rekeyTime: 2h
  ipsecPolicy:
    template: ipsec1
    espProposalId: 1
    encryptionAlgorithm: aes128-cbc
    authenticationAlgorithm: hmac-sha1
    esn: true
    replayWindow: 1024
    startAction: "start"
  vpn:
    name: vpn-secgw
    securityPolicyName: site-to-secgw-site
    svtiIdIn: 10
    svtiIdOut: 10
  interfaces:
    physical:
      name: eth1
      port: pci-b35s0
      interfaceCidr: 10.16.3.253/24
    loopback:
      name: lo0
      interfaceCidr: 1.1.1.1/32
    svti:
      name: svti-10
      id: 10
  routing:
    staticRoutes:
    - prefix: 2.2.2.2/32
      nextHop: svti-10
  ha:
    enabled: false
