# Number of CPUs used for the pod.
# The minimum is 2.
cpu: 3
# Amount of standard memory for the pod.
# The recommended value is 2Gi.
memory: 2Gi
# Amount of shared memory for the pod.
# The recommended value is 2Gi.
shared_memory: 2Gi
# Amount of hugepages for the pod.
# The recommended value for reserved_size is 6Gi.
# The possible value for page_size 2Mi or 1Gi, depending on
# what is available on the host.
hugepages:
  page_size: 2Mi
  reserved_size: 6Gi
# The container image
replicaCount: 1
image:
  repository: download.6wind.com/vsr/x86_64-ce/3.9
  tag: 3.9.4
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""
# List of PCI network devices to be added to the pod.
# The name must correpond to the metadata name in the
# NetworkAttachmentDefinition of multus configuration.
# The resource name must correspond to the one specified in the
# sriov plugin configuration.
ports:
- name: sriov
  resource_name: intel.com/sriovpass
- name: sriov2
  resource_name: intel.com/sriovpass2

# Day-1 configuration that will be rendered into a ConfigMap.
# All IP addresses live under the addresses collection so a single block
# controls the different instances (VSR1/VSR2/VSR3).
day1Config:
  enabled: true
  # Override the ConfigMap name if needed, otherwise <release>-day1-config is used.
  configMapName: ""
  licenseKey: "<LICENSE PROVIDED BY WG02 TEAM>"
  hostname: VSR1
  fastPath:
    port: pci-b0s6
  # preSharedKey:
  #   name: secgw
  #   secret: sylva0123456789
  # addresses:
  #   ha:
  #     local: 192.168.1.2
  #     remote: 192.168.1.3
  #   vpn:
  #     local: 192.168.1.1
  #     remote: 192.168.1.4
  #   trafficSelectors:
  #     local: 2.2.2.2/32
  #     remote: 1.1.1.1/32
  #   physicalInterfaceCidr: 192.168.1.2/24
  #   loopbackCidr: 2.2.2.2/32
  #   vrrpVirtualCidr: 192.168.1.1/24
  # ikePolicy:
  #   template: ike1
  #   proposalId: 1
  #   encryptionAlgorithm: aes128-cbc
  #   authenticationAlgorithm: hmac-sha1
  #   dhGroup: modp1024
  #   rekeyTime: 2h
  # ipsecPolicy:
  #   template: ipsec1
  #   espProposalId: 1
  #   encryptionAlgorithm: aes128-cbc
  #   authenticationAlgorithm: hmac-sha1
  #   esn: true
  #   replayWindow: 1024
  #   startAction: ""
  # vpn:
  #   name: vpn-secgw
  #   securityPolicyName: site-to-secgw-site
  #   svtiIdIn: 10
  #   svtiIdOut: 10
  # interfaces:
  #   physical:
  #     name: eth1
  #     port: pci-b0s6
  #   loopback:
  #     name: lo0
  #   svti:
  #     name: svti-10
  #     id: 10
  # routing:
  #   staticRoutes:
  #   - prefix: 1.1.1.1/32
  #     nextHop: svti-10
  # ha:
  #   enabled: true
  #   groupName: ha-group1
  #   listenGroup: ha-group1
  #   vrrp:
  #     enabled: true
  #     name: vrrp_ha
  #     version: 3
  #     linkInterface: eth1
  #     vrid: 1
  #     priority: 200
  #     notifyGroup: ""
